name: Update cask.json
on:
  push:
    paths:
      - .github/workflows/scheduled.yml
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  save-api:
    name: Save api output
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch homebrew/cask
        run: curl https://formulae.brew.sh/api/cask.json > raw.json

      - name: Update data for homebrew/cask
        run: (printf '[\n'; jq -c 'map(del(.tap_git_head,.tap,.installed_time,.installed,.ruby_source_path,.ruby_source_checksum))[]' raw.json | sed 's/^/\t/;s/$/,/' | head -c -2; printf '\n]\n') > cask.json && rm raw.json

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Update api output'
          default_author: github_actions
