name: Scheduled regeneration
on:
  push:
    paths:
      - .github/workflows/scheduled.yml
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  save-api:
    name: Save api output
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update data for homebrew/cask
        run: curl https://formulae.brew.sh/api/cask.json > cask.json

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Update api output'
          default_author: github_actions
